### ISSUE TITLE
4.5下无法生成

### ISSUE THREAD

**Issue by ragnaroks** [YangFan789/FadeJson#1]
![qq 20151202104023](https://cloud.githubusercontent.com/assets/7598199/11520740/1e5fafb2-98e1-11e5-9dda-d421d17dde00.png)

**Comment by YangFan789** [comment]
因为FadeJson用到了C#6的一些特性，所以无法在.NET Framework 4.5下编译。
对于这段代码，可以改成

```
public IEnumerable<JsonValue> Values {
    get{
        return dictionary.Values.Concat(list);
    }
}
```
其他使用`=>`实现的属性同理，也可这样更改

**Comment by ragnaroks** [comment]
soga,我目前还是自己实现了json(反)序列化,fastjson好像是不需要实体的?就像json.net里面那个匿名(反)序列化?

**Comment by YangFan789** [comment]
是的，并不需要实体类。但是FadeJson提供了生成实体类的工具。

**Comment by ragnaroks** [comment]
好的,下个项目观摩一下
